name: Build TCF Backend Golang

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build to Server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod tidy

      - name: Create Env File
        env:
          PROD_ENV: ${{ secrets.PROD_ENV }}
        run: |
          echo "$PROD_ENV" > .env

      - name: Build the app
        run: npm build
