name: Build TCF Backend Golang

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build to Server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        run: |
          export PATH=$PATH:/usr/local/go/bin
          export GOROOT=/usr/local/go
          export GOPATH=$HOME/go
          echo "GOROOT=$GOROOT" >> $GITHUB_ENV
          echo "GOPATH=$GOPATH" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Verify Go Installation
        run: |
          which go
          go version

      - name: Install dependencies
        run: go mod tidy

      - name: Create Env File
        env:
          PROD_ENV: ${{ secrets.PROD_ENV }}
        run: |
          echo "$PROD_ENV" > .env

      - name: Build the app
        run: go build
